package Karyawan;

import Koneksi.Koneksi;
import Login.session;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

public class FormEditService extends javax.swing.JFrame {

    protected int ID;

    public void setID(int ID) {
        this.ID = ID;
    }

    public int getID() {
        return ID;
    }
    
    Connection conn;
    Statement stmt;    
    PreparedStatement ps;
    ResultSet rs;
      
    private void AddTeknisi() {
        try {       
            conn = Koneksi.getConnection();
            stmt = conn.createStatement();
            String query = "SELECT IdTeknisi FROM DataTeknisi";
            rs = stmt.executeQuery(query);

            while (rs.next()) {
                String idTeknisi = rs.getString(1);
                cbxIdTeknisiEdit.addItem(idTeknisi);

            }

            rs.close();
            stmt.close();
        } catch (Exception Error) {
            System.out.println("" + Error);
        }
    }
    
    public FormEditService() {
        initComponents();
        
        txtNamaTeknisiEdit.setEditable(false);
        txtKeahlianTeknisiEdit.setEditable(false);
        txtNoHpTeknisiEdit.setEditable(false);
        
        AddTeknisi();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        dtpTanggalEdit = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        txtNamaEdit = new javax.swing.JTextField();
        txtNoHpEdit = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbxDiagnosisEdit = new javax.swing.JComboBox<>();
        txtMerekHpEdit = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        cbxIdTeknisiEdit = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txtKeahlianTeknisiEdit = new javax.swing.JTextField();
        txtNoHpTeknisiEdit = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtNamaTeknisiEdit = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Tanggal Service");

        dtpTanggalEdit.setBackground(new java.awt.Color(175, 211, 226));
        dtpTanggalEdit.setForeground(new java.awt.Color(0, 0, 0));
        dtpTanggalEdit.setDateFormatString("dd-MM-yyyy");

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Nama");

        txtNamaEdit.setBackground(new java.awt.Color(175, 211, 226));

        txtNoHpEdit.setBackground(new java.awt.Color(175, 211, 226));

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Nomor Handphone");

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Merek & Seri Handphone");

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Diagnosis Kerusakan");

        cbxDiagnosisEdit.setBackground(new java.awt.Color(175, 211, 226));
        cbxDiagnosisEdit.setForeground(new java.awt.Color(255, 255, 255));
        cbxDiagnosisEdit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Software", "Hardware" }));

        txtMerekHpEdit.setBackground(new java.awt.Color(175, 211, 226));

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Data Teknisi");

        jSeparator1.setBackground(new java.awt.Color(20, 108, 148));
        jSeparator1.setForeground(new java.awt.Color(20, 108, 148));

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("ID");

        cbxIdTeknisiEdit.setBackground(new java.awt.Color(175, 211, 226));
        cbxIdTeknisiEdit.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cbxIdTeknisiEditFocusLost(evt);
            }
        });

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Keahlian");

        txtKeahlianTeknisiEdit.setBackground(new java.awt.Color(175, 211, 226));

        txtNoHpTeknisiEdit.setBackground(new java.awt.Color(175, 211, 226));

        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("No Hp");

        txtNamaTeknisiEdit.setBackground(new java.awt.Color(175, 211, 226));

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Nama");

        btnSimpan.setBackground(new java.awt.Color(25, 167, 206));
        btnSimpan.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        btnSimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpan.setText("Update");
        btnSimpan.setBorder(null);
        btnSimpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSimpanMouseClicked(evt);
            }
        });

        btnCancel.setBackground(new java.awt.Color(25, 167, 206));
        btnCancel.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("Cancel");
        btnCancel.setBorder(null);
        btnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(49, 49, 49)
                                .addComponent(txtNamaTeknisiEdit))
                            .addComponent(dtpTanggalEdit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNamaEdit, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMerekHpEdit, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                                .addComponent(cbxIdTeknisiEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4)
                            .addComponent(txtNoHpEdit)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel9))
                                .addGap(33, 33, 33)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtKeahlianTeknisiEdit)
                                    .addComponent(txtNoHpTeknisiEdit)))
                            .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxDiagnosisEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dtpTanggalEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNamaEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNoHpEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMerekHpEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxDiagnosisEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(cbxIdTeknisiEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNamaTeknisiEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtKeahlianTeknisiEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNoHpTeknisiEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cbxIdTeknisiEditFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbxIdTeknisiEditFocusLost
        try {
            conn = Koneksi.getConnection();
                        
            String idTeknisi = cbxIdTeknisiEdit.getSelectedItem().toString();
            String query = "SELECT * FROM DataTeknisi WHERE IdTeknisi = ?";
            ps = conn.prepareStatement(query);
            ps.setString(1, idTeknisi);
            rs = ps.executeQuery();

            if (rs.next()) {
                String namaTeknisi = rs.getString("Nama");
                String keahlian = rs.getString("Keahlian");
                String noHpTeknisi = rs.getString("NoHp");

                txtNamaTeknisiEdit.setText(namaTeknisi);
                txtKeahlianTeknisiEdit.setText(keahlian);
                txtNoHpTeknisiEdit.setText(noHpTeknisi);
            }
            
            rs.close();
            ps.close();
        } catch (Exception Error) {
            System.out.println("" + Error);
        }
    }//GEN-LAST:event_cbxIdTeknisiEditFocusLost

    private void btnCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseClicked
        setVisible(false);
        
        LihatDataService lihat = new LihatDataService();
        lihat.setVisible(true);
    }//GEN-LAST:event_btnCancelMouseClicked

    private void btnSimpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSimpanMouseClicked
        String Nama, NoHp, Merek, Diagnosis, NamaTeknisi, KeahlianTeknisi, NoHpTeknisi;
        int IDTeknisi;
        
        String tampilan = "dd-MM-yyyy";
        SimpleDateFormat fm = new SimpleDateFormat(tampilan);
        String tanggal = "";
        
        if (dtpTanggalEdit.getDate() != null) {
            tanggal = fm.format(dtpTanggalEdit.getDate());
        } else {
            JOptionPane.showMessageDialog(this, "Pilih Tanggal & Perhatikan Format.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
       
        Nama = txtNamaEdit.getText();
        NoHp = txtNoHpEdit.getText();
        Merek = txtMerekHpEdit.getText();
        Diagnosis = cbxDiagnosisEdit.getSelectedItem().toString();
        
        IDTeknisi = Integer.parseInt(cbxIdTeknisiEdit.getSelectedItem().toString());
        NamaTeknisi = txtNamaTeknisiEdit.getText();
        KeahlianTeknisi = txtKeahlianTeknisiEdit.getText();
        NoHpTeknisi = txtNoHpTeknisiEdit.getText();
        
        try {
            conn = Koneksi.getConnection();
            stmt = conn.createStatement();
            
            if (Nama.isEmpty()) {
                txtNamaEdit.requestFocus();
                JOptionPane.showMessageDialog(this, "Nama Tidak Boleh Kosong.", "Error", JOptionPane.ERROR_MESSAGE);
            }
            else if (NoHp.isEmpty()) {
                txtNoHpEdit.requestFocus();
                JOptionPane.showMessageDialog(this, "Nomor Hp Customer Tidak Boleh Kosong.", "Error", JOptionPane.ERROR_MESSAGE);
            }
            else if (Merek.isEmpty()) {
                txtMerekHpEdit.requestFocus();
                JOptionPane.showMessageDialog(this, "Merek Hp Tidak Boleh Kosong.", "Error", JOptionPane.ERROR_MESSAGE);
            }
            else if (Diagnosis.isEmpty()){
                cbxDiagnosisEdit.requestFocus();
                JOptionPane.showMessageDialog(this, "Diagnosis Tidak Boleh Kosong.", "Error", JOptionPane.ERROR_MESSAGE);
            }
            else if (IDTeknisi == 0){
                cbxIdTeknisiEdit.requestFocus();
                JOptionPane.showMessageDialog(this, "Id Teknisi Tidak Boleh Kosong.", "Error", JOptionPane.ERROR_MESSAGE);
            }
            else if ((txtNamaTeknisiEdit.getText()).isEmpty()){
                cbxIdTeknisiEdit.requestFocus();
                JOptionPane.showMessageDialog(this, "Nama, NoHp, & Keahlian Teknisi Tidak Boleh Kosong.", "Error", JOptionPane.ERROR_MESSAGE);
            }else{
                
                // Query Update
                String sql = "UPDATE DataService SET TanggalService = ?, NamaCust = ?, NoHpCust = ?, MerekHp = ?, Diagnosis = ?, IdTeknisi = ?, Namateknisi = ?, KeahlianTeknisi = ?, NoHpTeknisi = ? WHERE IdService = ?";
                PreparedStatement ps = conn.prepareStatement(sql);
                ps.setString(1, tanggal);
                ps.setString(2, Nama);
                ps.setString(3, NoHp);
                ps.setString(4, Merek);
                ps.setString(5, Diagnosis);
                ps.setInt(6, IDTeknisi);
                ps.setString(7, NamaTeknisi);
                ps.setString(8, KeahlianTeknisi);
                ps.setString(9, NoHpTeknisi);
                ps.setInt(10, getID());
                ps.executeUpdate();
                ps.close();

                JOptionPane.showMessageDialog(this, "Data Service Telah Berhasil Di Simpan!", "Informasi", JOptionPane.INFORMATION_MESSAGE); 

                setVisible(false);
        
                LihatDataService lihat = new LihatDataService();
                lihat.setVisible(true);
            }

        }catch (Exception Error) {
            System.out.println("" + Error);
        }
        
    }//GEN-LAST:event_btnSimpanMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormEditService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormEditService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormEditService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormEditService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormEditService().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSimpan;
    public javax.swing.JComboBox<String> cbxDiagnosisEdit;
    public javax.swing.JComboBox<String> cbxIdTeknisiEdit;
    public com.toedter.calendar.JDateChooser dtpTanggalEdit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JTextField txtKeahlianTeknisiEdit;
    public javax.swing.JTextField txtMerekHpEdit;
    public javax.swing.JTextField txtNamaEdit;
    public javax.swing.JTextField txtNamaTeknisiEdit;
    public javax.swing.JTextField txtNoHpEdit;
    public javax.swing.JTextField txtNoHpTeknisiEdit;
    // End of variables declaration//GEN-END:variables
}
