package Karyawan;

import Koneksi.Koneksi;
import Login.session;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

public class FormTambahService extends javax.swing.JFrame {

    Connection conn;
    Statement stmt;
    PreparedStatement ps;
    ResultSet rs;
    
   private void AddTeknisi() {
        try {       
            conn = Koneksi.getConnection();
            stmt = conn.createStatement();
            String query = "SELECT IdTeknisi FROM DataTeknisi";
            rs = stmt.executeQuery(query);

            while (rs.next()) {
                String idTeknisi = rs.getString(1);
                cbxIdTeknisi.addItem(idTeknisi);
                
            }
            
            rs.close();
            stmt.close();
        } catch (Exception Error) {
            System.out.println("" + Error);
        }
    }
    
    public FormTambahService() {
        initComponents();
        
        txtNamaTeknisi.setEditable(false);
        txtKeahlianTeknisi.setEditable(false);
        txtNoHpTeknisi.setEditable(false);
        AddTeknisi();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtMerekHp = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbxDiagnosis = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtNoHp = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        dtpTanggal = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        cbxIdTeknisi = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        txtNamaTeknisi = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtKeahlianTeknisi = new javax.swing.JTextField();
        txtNoHpTeknisi = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Nama");

        txtNama.setBackground(new java.awt.Color(175, 211, 226));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Merek & Seri Handphone");

        txtMerekHp.setBackground(new java.awt.Color(175, 211, 226));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Diagnosis Kerusakan");

        cbxDiagnosis.setBackground(new java.awt.Color(175, 211, 226));
        cbxDiagnosis.setForeground(new java.awt.Color(255, 255, 255));
        cbxDiagnosis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Software", "Hardware" }));

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Nomor Handphone");

        txtNoHp.setBackground(new java.awt.Color(175, 211, 226));

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Tanggal Service");

        dtpTanggal.setBackground(new java.awt.Color(175, 211, 226));
        dtpTanggal.setForeground(new java.awt.Color(0, 0, 0));
        dtpTanggal.setDateFormatString("dd-MM-yyyy");

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Data Teknisi");

        jSeparator1.setBackground(new java.awt.Color(20, 108, 148));
        jSeparator1.setForeground(new java.awt.Color(20, 108, 148));

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("ID");

        cbxIdTeknisi.setBackground(new java.awt.Color(175, 211, 226));
        cbxIdTeknisi.setForeground(new java.awt.Color(255, 255, 255));
        cbxIdTeknisi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cbxIdTeknisiFocusLost(evt);
            }
        });

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Nama");

        txtNamaTeknisi.setBackground(new java.awt.Color(175, 211, 226));

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Keahlian");

        txtKeahlianTeknisi.setBackground(new java.awt.Color(175, 211, 226));

        txtNoHpTeknisi.setBackground(new java.awt.Color(175, 211, 226));

        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("No Hp");

        btnCancel.setBackground(new java.awt.Color(25, 167, 206));
        btnCancel.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("Cancel");
        btnCancel.setBorder(null);
        btnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelMouseClicked(evt);
            }
        });

        btnSimpan.setBackground(new java.awt.Color(25, 167, 206));
        btnSimpan.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        btnSimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpan.setText("Simpan");
        btnSimpan.setBorder(null);
        btnSimpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSimpanMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(49, 49, 49)
                                .addComponent(txtNamaTeknisi))
                            .addComponent(dtpTanggal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNama, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMerekHp, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                                .addComponent(cbxIdTeknisi, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4)
                            .addComponent(txtNoHp)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel9))
                                .addGap(33, 33, 33)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtKeahlianTeknisi, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                                    .addComponent(txtNoHpTeknisi)))
                            .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxDiagnosis, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dtpTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNoHp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMerekHp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxDiagnosis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(cbxIdTeknisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNamaTeknisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtKeahlianTeknisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNoHpTeknisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSimpanMouseClicked
        String loggedInUsername = session.getLoggedInUsername();
        
        String Nama, NoHp, Merek, Diagnosis, NamaTeknisi, KeahlianTeknisi, NoHpTeknisi;
        int IDTeknisi;
        
        String tampilan = "dd-MM-yyyy";
        SimpleDateFormat fm = new SimpleDateFormat(tampilan);
        String tanggal = "";
        
        if (dtpTanggal.getDate() != null) {
            tanggal = fm.format(dtpTanggal.getDate());
        } else {
            JOptionPane.showMessageDialog(this, "Pilih Tanggal & Perhatikan Format.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
       
        Nama = txtNama.getText();
        NoHp = txtNoHp.getText();
        Merek = txtMerekHp.getText();
        Diagnosis = cbxDiagnosis.getSelectedItem().toString();
        
        IDTeknisi = Integer.parseInt(cbxIdTeknisi.getSelectedItem().toString());
        NamaTeknisi = txtNamaTeknisi.getText();
        KeahlianTeknisi = txtKeahlianTeknisi.getText();
        NoHpTeknisi = txtNoHpTeknisi.getText();
        
        try {
            conn = Koneksi.getConnection();
            stmt = conn.createStatement();
            
            if (Nama.isEmpty()) {
                txtNama.requestFocus();
                JOptionPane.showMessageDialog(this, "Nama Tidak Boleh Kosong.", "Error", JOptionPane.ERROR_MESSAGE);
            }
            else if (NoHp.isEmpty()) {
                txtNoHp.requestFocus();
                JOptionPane.showMessageDialog(this, "Nomor Hp Customer Tidak Boleh Kosong.", "Error", JOptionPane.ERROR_MESSAGE);
            }
            else if (Merek.isEmpty()) {
                txtMerekHp.requestFocus();
                JOptionPane.showMessageDialog(this, "Merek Hp Tidak Boleh Kosong.", "Error", JOptionPane.ERROR_MESSAGE);
            }
            else if (Diagnosis.isEmpty()){
                cbxDiagnosis.requestFocus();
                JOptionPane.showMessageDialog(this, "Diagnosis Tidak Boleh Kosong.", "Error", JOptionPane.ERROR_MESSAGE);
            }
            else if (IDTeknisi == 0){
                cbxIdTeknisi.requestFocus();
                JOptionPane.showMessageDialog(this, "Id Teknisi Tidak Boleh Kosong.", "Error", JOptionPane.ERROR_MESSAGE);
            }
            else if ((txtNamaTeknisi.getText()).isEmpty()){
                cbxIdTeknisi.requestFocus();
                JOptionPane.showMessageDialog(this, "Nama, NoHp, & Keahlian Teknisi Tidak Boleh Kosong.", "Error", JOptionPane.ERROR_MESSAGE);
            }else{
                
                // Query Simpan
                String sql = "INSERT INTO DataService (TanggalService, NamaCust, NoHpCust, MerekHp, Diagnosis, IdTeknisi, Namateknisi, KeahlianTeknisi, NoHpTeknisi, Username) VALUES ('%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s')";
                sql = String.format(sql, tanggal, Nama, NoHp, Merek, Diagnosis, IDTeknisi, NamaTeknisi, KeahlianTeknisi, NoHpTeknisi, loggedInUsername);


                // Eksekusi
                stmt.execute(sql);

                JOptionPane.showMessageDialog(this, "Data Service Telah Berhasil Di Simpan!", "Informasi", JOptionPane.INFORMATION_MESSAGE); 

                setVisible(false);
            }

        }catch (Exception Error) {
            System.out.println("" + Error);
        }
        
    }//GEN-LAST:event_btnSimpanMouseClicked
    
    private void cbxIdTeknisiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbxIdTeknisiFocusLost
        try {
            conn = Koneksi.getConnection();
                        
            String idTeknisi = cbxIdTeknisi.getSelectedItem().toString();
            String query = "SELECT * FROM DataTeknisi WHERE IdTeknisi = ?";
            ps = conn.prepareStatement(query);
            ps.setString(1, idTeknisi);
            rs = ps.executeQuery();

            if (rs.next()) {
                String namaTeknisi = rs.getString("Nama");
                String keahlian = rs.getString("Keahlian");
                String noHpTeknisi = rs.getString("NoHp");

                txtNamaTeknisi.setText(namaTeknisi);
                txtKeahlianTeknisi.setText(keahlian);
                txtNoHpTeknisi.setText(noHpTeknisi);
            }
            
            rs.close();
            ps.close();
        } catch (Exception Error) {
            System.out.println("" + Error);
        }
    }//GEN-LAST:event_cbxIdTeknisiFocusLost

    private void btnCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseClicked
        setVisible(false);
    }//GEN-LAST:event_btnCancelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormTambahService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormTambahService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormTambahService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormTambahService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormTambahService().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<String> cbxDiagnosis;
    private javax.swing.JComboBox<String> cbxIdTeknisi;
    private com.toedter.calendar.JDateChooser dtpTanggal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtKeahlianTeknisi;
    private javax.swing.JTextField txtMerekHp;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNamaTeknisi;
    private javax.swing.JTextField txtNoHp;
    private javax.swing.JTextField txtNoHpTeknisi;
    // End of variables declaration//GEN-END:variables
}
