package Karyawan;

import Admin.FormEdit;
import Koneksi.Koneksi;
import Login.session;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class LihatDataService extends javax.swing.JFrame {
    
    Connection conn;
    Statement stmt;
    ResultSet rs;
    PreparedStatement ps;
    
    private DefaultTableModel model;
        
    public LihatDataService() {
        initComponents();
        
        model = new DefaultTableModel();
        tabelservice.setModel(model);
        model.addColumn("ID");
        model.addColumn("Tanggal");
        model.addColumn("Customer");
        model.addColumn("No Hp Customer");
        model.addColumn("Merek Handphone");
        model.addColumn("Diagnosis Kerusakan");
        model.addColumn("Nama Teknisi");
        model.addColumn("Keahlian Teknisi");
        model.addColumn("No Hp Teknisi");
        
        ShowData();
    }
    
    
    public void ShowData(){
        String loggedInUsername = session.getLoggedInUsername();
        
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        
        try{
            conn = Koneksi.getConnection();
            stmt = conn.createStatement();
            
            // Query Lihat
            String sql = "SELECT * FROM DataService WHERE Username = '%s'";
            sql = String.format(sql, loggedInUsername); 

            // Eksekusi
            rs = stmt.executeQuery(sql);
            while(rs.next()){
                Object[] o = new Object[9];
                o[0] = rs.getInt("IdService");
                o[1] = rs.getString("TanggalService");
                o[2] = rs.getString("NamaCust");
                o[3] = rs.getString("NoHpCust");
                o[4] = rs.getString("MerekHp");
                o[5] = rs.getString("Diagnosis");
                o[6] = rs.getString("NamaTeknisi");
                o[7] = rs.getString("KeahlianTeknisi");
                o[8] = rs.getString("NoHpTeknisi");
                model.addRow(o);
            }
            rs.close();
            stmt.close();
            
        }catch (Exception Error){
            System.out.println("" + Error);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelservice = new javax.swing.JTable();
        btnKembali = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tabelservice.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Tanggal", "Customer", "No HP Customer", "Merek Handphone", "Diagnosis Kerusakan", "Nama Teknisi", "Keahlian Teknisi", "No HP Teknisi"
            }
        ));
        jScrollPane1.setViewportView(tabelservice);

        btnKembali.setBackground(new java.awt.Color(25, 167, 206));
        btnKembali.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        btnKembali.setForeground(new java.awt.Color(255, 255, 255));
        btnKembali.setText("Kembali");
        btnKembali.setBorder(null);
        btnKembali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnKembaliMouseClicked(evt);
            }
        });

        btnHapus.setBackground(new java.awt.Color(25, 167, 206));
        btnHapus.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setText("Hapus");
        btnHapus.setBorder(null);
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnEdit.setBackground(new java.awt.Color(25, 167, 206));
        btnEdit.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setText("Edit");
        btnEdit.setBorder(null);
        btnEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 822, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        int i = tabelservice.getSelectedRow();
        if (i == -1){
            JOptionPane.showMessageDialog(this, "Pilih Data Pada Tabel.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        int ID = Integer.parseInt(model.getValueAt(i, 0).toString());
        
        try{
            conn = Koneksi.getConnection();
            
            // Query Hapus
            String sql = "DELETE FROM DataService WHERE IdService = ?";
            ps = conn.prepareStatement(sql);
            ps.setInt(1, ID);
            ps.executeUpdate();
            ps.close();
            
            
        }catch (Exception Error){
            System.out.println("" + Error);
        }finally{
            ShowData();
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnKembaliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKembaliMouseClicked
        setVisible(false);
    }//GEN-LAST:event_btnKembaliMouseClicked

    private void btnEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditMouseClicked
        int i = tabelservice.getSelectedRow();
        if (i == -1){
            JOptionPane.showMessageDialog(this, "Pilih Data Pada Tabel.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        int ID = Integer.parseInt(model.getValueAt(i, 0).toString());
        
        FormEditService edit = new FormEditService();
        edit.setID(ID);
        
        String Tanggal, Nama, NoHp, MerekHp, Diagnosis, IdTeknisi;
        
        try {
            Tanggal = (String) model.getValueAt(i, 1);

            // Ubah tanggal dari tipe String menjadi tipe Date
            SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
            Date tanggal = dateFormat.parse(Tanggal);

            // Set nilai tanggal pada JDateChooser
            edit.dtpTanggalEdit.setDate(tanggal);
        } catch (Exception Error){
            System.out.println("" + Error);
        }
        
        Nama = (String) model.getValueAt(i, 2);
        
        edit.txtNamaEdit.setText(Nama);
        
        
        NoHp = (String) model.getValueAt(i, 3);
        
        edit.txtNoHpEdit.setText(NoHp);
        
        MerekHp = (String) model.getValueAt(i, 4);
        
        edit.txtMerekHpEdit.setText(MerekHp);
        
        Diagnosis = (String) model.getValueAt(i, 5);
        
        edit.cbxDiagnosisEdit.setSelectedItem(Diagnosis);
        
        try {
            conn = Koneksi.getConnection();

            // Query SELECT
            String sql = "SELECT * FROM DataService WHERE IdService = ?";
            ps = conn.prepareStatement(sql);
            ps.setInt(1, ID);
            rs = ps.executeQuery();

            if (rs.next()) {
                // Ambil nilai dari hasil query
                int IDTeknisi = rs.getInt("IdTeknisi");
                String NamaTeknisi = rs.getString("Namateknisi");
                String KeahlianTeknisi = rs.getString("KeahlianTeknisi");
                String NoHpTeknisi = rs.getString("NoHpTeknisi");

                edit.cbxIdTeknisiEdit.setSelectedItem(String.valueOf(IDTeknisi));
                edit.txtNamaTeknisiEdit.setText(NamaTeknisi);
                edit.txtKeahlianTeknisiEdit.setText(KeahlianTeknisi);
                edit.txtNoHpTeknisiEdit.setText(NoHpTeknisi);
            }

            rs.close();
            ps.close();
        } catch (Exception Error) {
            System.out.println("" + Error);
        }
    
        setVisible(false);
        edit.setVisible(true);
    }//GEN-LAST:event_btnEditMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LihatDataService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LihatDataService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LihatDataService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LihatDataService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LihatDataService().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKembali;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelservice;
    // End of variables declaration//GEN-END:variables

    private void setVisibile(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
